const MASTER_IMAGE_REGISTRY = [
    "collections/Belgrade/Belgrade_1.jpg",
    "collections/Belgrade/Belgrade_10.jpg",
    "collections/Belgrade/Belgrade_11.jpg",
    "collections/Belgrade/Belgrade_12.jpg",
    "collections/Belgrade/Belgrade_13.jpg",
    "collections/Belgrade/Belgrade_14.jpg",
    "collections/Belgrade/Belgrade_15.jpg",
    "collections/Belgrade/Belgrade_16.jpg",
    "collections/Belgrade/Belgrade_17.jpg",
    "collections/Belgrade/Belgrade_18.jpg",
    "collections/Belgrade/Belgrade_19.jpg",
    "collections/Belgrade/Belgrade_2.jpg",
    "collections/Belgrade/Belgrade_3.jpg",
    "collections/Belgrade/Belgrade_4.jpg",
    "collections/Belgrade/Belgrade_5.jpg",
    "collections/Belgrade/Belgrade_6.jpg",
    "collections/Belgrade/Belgrade_7.jpg",
    "collections/Belgrade/Belgrade_8.jpg",
    "collections/Belgrade/Belgrade_9.jpg",
    "collections/Chroma/Chroma_0.jpg",
    "collections/Chroma/Chroma_1.jpg",
    "collections/Chroma/Chroma_10.jpg",
    "collections/Chroma/Chroma_11.jpg",
    "collections/Chroma/Chroma_12.jpg",
    "collections/Chroma/Chroma_13.jpg",
    "collections/Chroma/Chroma_14.jpg",
    "collections/Chroma/Chroma_15.jpg",
    "collections/Chroma/Chroma_16.jpg",
    "collections/Chroma/Chroma_17.jpg",
    "collections/Chroma/Chroma_18.jpg",
    "collections/Chroma/Chroma_19.jpg",
    "collections/Chroma/Chroma_2.jpg",
    "collections/Chroma/Chroma_20.jpg",
    "collections/Chroma/Chroma_21.jpg",
    "collections/Chroma/Chroma_3.jpg",
    "collections/Chroma/Chroma_4.jpg",
    "collections/Chroma/Chroma_5.jpg",
    "collections/Chroma/Chroma_6.jpg",
    "collections/Chroma/Chroma_7.jpg",
    "collections/Chroma/Chroma_8.jpg",
    "collections/Chroma/Chroma_9.jpg",
    "collections/Hangzhou/Hangzhou_1.jpg",
    "collections/Hangzhou/Hangzhou_10.jpg",
    "collections/Hangzhou/Hangzhou_11.jpg",
    "collections/Hangzhou/Hangzhou_12.jpg",
    "collections/Hangzhou/Hangzhou_13.jpg",
    "collections/Hangzhou/Hangzhou_14.jpg",
    "collections/Hangzhou/Hangzhou_15.jpg",
    "collections/Hangzhou/Hangzhou_16.jpg",
    "collections/Hangzhou/Hangzhou_17.jpg",
    "collections/Hangzhou/Hangzhou_18.jpg",
    "collections/Hangzhou/Hangzhou_19.jpg",
    "collections/Hangzhou/Hangzhou_2.jpg",
    "collections/Hangzhou/Hangzhou_20.jpg",
    "collections/Hangzhou/Hangzhou_3.jpg",
    "collections/Hangzhou/Hangzhou_4.jpg",
    "collections/Hangzhou/Hangzhou_5.jpg",
    "collections/Hangzhou/Hangzhou_6.jpg",
    "collections/Hangzhou/Hangzhou_7.jpg",
    "collections/Hangzhou/Hangzhou_8.jpg",
    "collections/Hangzhou/Hangzhou_9.jpg",
    "collections/homepage/ascii-art (3).png",
    "collections/homepage/ascii-art (4).png",
    "collections/homepage/Belgrade_1.jpg",
    "collections/homepage/Belgrade_4.jpg",
    "collections/homepage/Chroma_0.jpg",
    "collections/homepage/dark-icon.png",
    "collections/homepage/Fan_tail_L.jpg",
    "collections/homepage/Harbour.jpg",
    "collections/homepage/light-icon.png",
    "collections/homepage/magnifier-icon.png",
    "collections/homepage/TuiPark_Kauri_Park.jpg",
    "collections/Music/Music_1.jpg",
    "collections/Music/Music_10.jpg",
    "collections/Music/Music_11.jpg",
    "collections/Music/Music_12.jpg",
    "collections/Music/Music_13.jpg",
    "collections/Music/Music_14.jpg",
    "collections/Music/Music_15.jpg",
    "collections/Music/Music_16.jpg",
    "collections/Music/Music_17.jpg",
    "collections/Music/Music_18.jpg",
    "collections/Music/Music_19.jpg",
    "collections/Music/Music_2.jpg",
    "collections/Music/Music_20.jpg",
    "collections/Music/Music_21.jpg",
    "collections/Music/Music_22.jpg",
    "collections/Music/Music_23.jpg",
    "collections/Music/Music_24.jpg",
    "collections/Music/Music_25.jpg",
    "collections/Music/Music_3.jpg",
    "collections/Music/Music_4.jpg",
    "collections/Music/Music_5.jpg",
    "collections/Music/Music_6.jpg",
    "collections/Music/Music_7.jpg",
    "collections/Music/Music_8.jpg",
    "collections/Music/Music_9.jpg",
    "collections/South Island/South Island_1.jpg",
    "collections/South Island/South Island_10.jpg",
    "collections/South Island/South Island_11.jpg",
    "collections/South Island/South Island_12.jpg",
    "collections/South Island/South Island_13.jpg",
    "collections/South Island/South Island_14.jpg",
    "collections/South Island/South Island_15.jpg",
    "collections/South Island/South Island_16.jpg",
    "collections/South Island/South Island_17.jpg",
    "collections/South Island/South Island_18.jpg",
    "collections/South Island/South Island_19.jpg",
    "collections/South Island/South Island_2.jpg",
    "collections/South Island/South Island_20.jpg",
    "collections/South Island/South Island_21.jpg",
    "collections/South Island/South Island_22.jpg",
    "collections/South Island/South Island_23.jpg",
    "collections/South Island/South Island_24.jpg",
    "collections/South Island/South Island_3.jpg",
    "collections/South Island/South Island_4.jpg",
    "collections/South Island/South Island_5.jpg",
    "collections/South Island/South Island_6.jpg",
    "collections/South Island/South Island_7.jpg",
    "collections/South Island/South Island_8.jpg",
    "collections/South Island/South Island_9.jpg",
    "collections/Walking/Walking_1.jpg",
    "collections/Walking/Walking_10.jpg",
    "collections/Walking/Walking_11.jpg",
    "collections/Walking/Walking_12.jpg",
    "collections/Walking/Walking_13.jpg",
    "collections/Walking/Walking_14.jpg",
    "collections/Walking/Walking_15.jpg",
    "collections/Walking/Walking_16.jpg",
    "collections/Walking/Walking_17.jpg",
    "collections/Walking/Walking_18.jpg",
    "collections/Walking/Walking_19.jpg",
    "collections/Walking/Walking_2.jpg",
    "collections/Walking/Walking_20.jpg",
    "collections/Walking/Walking_21.jpg",
    "collections/Walking/Walking_22.jpg",
    "collections/Walking/Walking_23.jpg",
    "collections/Walking/Walking_24.jpg",
    "collections/Walking/Walking_25.jpg",
    "collections/Walking/Walking_26.jpg",
    "collections/Walking/Walking_27.jpg",
    "collections/Walking/Walking_28.jpg",
    "collections/Walking/Walking_29.jpg",
    "collections/Walking/Walking_3.jpg",
    "collections/Walking/Walking_30.jpg",
    "collections/Walking/Walking_31.jpg",
    "collections/Walking/Walking_32.jpg",
    "collections/Walking/Walking_33.jpg",
    "collections/Walking/Walking_4.jpg",
    "collections/Walking/Walking_5.jpg",
    "collections/Walking/Walking_6.jpg",
    "collections/Walking/Walking_7.jpg",
    "collections/Walking/Walking_8.jpg",
    "collections/Walking/Walking_9.jpg"
];

// ============================================================
// CUSTOM DESCRIPTIONS - Edit the text inside the quotes!
// ============================================================
const CUSTOM_DESCRIPTIONS = {
    "collections/Belgrade/Belgrade_1.jpg": "Image description",
    "collections/Belgrade/Belgrade_2.jpg": "Image description",
    "collections/Belgrade/Belgrade_3.jpg": "Image description",
    "collections/Belgrade/Belgrade_4.jpg": "Image description",
    "collections/Belgrade/Belgrade_5.jpg": "Image description",
    "collections/Belgrade/Belgrade_6.jpg": "Image description",
    "collections/Belgrade/Belgrade_7.jpg": "Image description",
    "collections/Belgrade/Belgrade_8.jpg": "Image description",
    "collections/Belgrade/Belgrade_9.jpg": "Image description",
    "collections/Belgrade/Belgrade_10.jpg": "Image description",
    "collections/Belgrade/Belgrade_11.jpg": "Image description",
    "collections/Belgrade/Belgrade_12.jpg": "Image description",
    "collections/Belgrade/Belgrade_13.jpg": "Image description",
    "collections/Belgrade/Belgrade_14.jpg": "Image description",
    "collections/Belgrade/Belgrade_15.jpg": "Image description",
    "collections/Belgrade/Belgrade_16.jpg": "Image description",
    "collections/Belgrade/Belgrade_17.jpg": "Image description",
    "collections/Belgrade/Belgrade_18.jpg": "Image description",
    "collections/Belgrade/Belgrade_19.jpg": "Image description",
    "collections/Chroma/Chroma_0.jpg": "Image description",
    "collections/Chroma/Chroma_1.jpg": "Image description",
    "collections/Chroma/Chroma_2.jpg": "Image description",
    "collections/Chroma/Chroma_3.jpg": "Image description",
    "collections/Chroma/Chroma_4.jpg": "Image description",
    "collections/Chroma/Chroma_5.jpg": "Image description",
    "collections/Chroma/Chroma_6.jpg": "Image description",
    "collections/Chroma/Chroma_7.jpg": "Image description",
    "collections/Chroma/Chroma_8.jpg": "Image description",
    "collections/Chroma/Chroma_9.jpg": "Image description",
    "collections/Chroma/Chroma_10.jpg": "Image description",
    "collections/Chroma/Chroma_11.jpg": "Image description",
    "collections/Chroma/Chroma_12.jpg": "Image description",
    "collections/Chroma/Chroma_13.jpg": "Image description",
    "collections/Chroma/Chroma_14.jpg": "Image description",
    "collections/Chroma/Chroma_15.jpg": "Image description",
    "collections/Chroma/Chroma_16.jpg": "Image description",
    "collections/Chroma/Chroma_17.jpg": "Image description",
    "collections/Chroma/Chroma_18.jpg": "Image description",
    "collections/Chroma/Chroma_19.jpg": "Image description",
    "collections/Chroma/Chroma_20.jpg": "Image description",
    "collections/Chroma/Chroma_21.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_1.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_2.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_3.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_4.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_5.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_6.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_7.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_8.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_9.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_10.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_11.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_12.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_13.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_14.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_15.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_16.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_17.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_18.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_19.jpg": "Image description",
    "collections/Hangzhou/Hangzhou_20.jpg": "Image description",
    "collections/Music/Music_1.jpg": "Image description",
    "collections/Music/Music_2.jpg": "Image description",
    "collections/Music/Music_3.jpg": "Image description",
    "collections/Music/Music_4.jpg": "Image description",
    "collections/Music/Music_5.jpg": "Image description",
    "collections/Music/Music_6.jpg": "Image description",
    "collections/Music/Music_7.jpg": "Image description",
    "collections/Music/Music_8.jpg": "Image description",
    "collections/Music/Music_9.jpg": "Image description",
    "collections/Music/Music_10.jpg": "Image description",
    "collections/Music/Music_11.jpg": "Image description",
    "collections/Music/Music_12.jpg": "Image description",
    "collections/Music/Music_13.jpg": "Image description",
    "collections/Music/Music_14.jpg": "Image description",
    "collections/Music/Music_15.jpg": "Image description",
    "collections/Music/Music_16.jpg": "Image description",
    "collections/Music/Music_17.jpg": "Image description",
    "collections/Music/Music_18.jpg": "Image description",
    "collections/Music/Music_19.jpg": "Image description",
    "collections/Music/Music_20.jpg": "Image description",
    "collections/Music/Music_21.jpg": "Image description",
    "collections/Music/Music_22.jpg": "Image description",
    "collections/Music/Music_23.jpg": "Image description",
    "collections/Music/Music_24.jpg": "Image description",
    "collections/Music/Music_25.jpg": "Image description",
    "collections/South Island/South Island_1.jpg": "Image description",
    "collections/South Island/South Island_2.jpg": "Image description",
    "collections/South Island/South Island_3.jpg": "Image description",
    "collections/South Island/South Island_4.jpg": "Image description",
    "collections/South Island/South Island_5.jpg": "Image description",
    "collections/South Island/South Island_6.jpg": "Image description",
    "collections/South Island/South Island_7.jpg": "Image description",
    "collections/South Island/South Island_8.jpg": "Image description",
    "collections/South Island/South Island_9.jpg": "Image description",
    "collections/South Island/South Island_10.jpg": "Image description",
    "collections/South Island/South Island_11.jpg": "Image description",
    "collections/South Island/South Island_12.jpg": "Image description",
    "collections/South Island/South Island_13.jpg": "Image description",
    "collections/South Island/South Island_14.jpg": "Image description",
    "collections/South Island/South Island_15.jpg": "Image description",
    "collections/South Island/South Island_16.jpg": "Image description",
    "collections/South Island/South Island_17.jpg": "Image description",
    "collections/South Island/South Island_18.jpg": "Image description",
    "collections/South Island/South Island_19.jpg": "Image description",
    "collections/South Island/South Island_20.jpg": "Image description",
    "collections/South Island/South Island_21.jpg": "Image description",
    "collections/South Island/South Island_22.jpg": "Image description",
    "collections/South Island/South Island_23.jpg": "Image description",
    "collections/South Island/South Island_24.jpg": "Image description",
    "collections/Walking/Walking_1.jpg": "Image description",
    "collections/Walking/Walking_2.jpg": "Image description",
    "collections/Walking/Walking_3.jpg": "Image description",
    "collections/Walking/Walking_4.jpg": "Image description",
    "collections/Walking/Walking_5.jpg": "Image description",
    "collections/Walking/Walking_6.jpg": "Image description",
    "collections/Walking/Walking_7.jpg": "Image description",
    "collections/Walking/Walking_8.jpg": "Image description",
    "collections/Walking/Walking_9.jpg": "Image description",
    "collections/Walking/Walking_10.jpg": "Image description",
    "collections/Walking/Walking_11.jpg": "Image description",
    "collections/Walking/Walking_12.jpg": "Image description",
    "collections/Walking/Walking_13.jpg": "Image description",
    "collections/Walking/Walking_14.jpg": "Image description",
    "collections/Walking/Walking_15.jpg": "Image description",
    "collections/Walking/Walking_16.jpg": "Image description",
    "collections/Walking/Walking_17.jpg": "Image description",
    "collections/Walking/Walking_18.jpg": "Image description",
    "collections/Walking/Walking_19.jpg": "Image description",
    "collections/Walking/Walking_20.jpg": "Image description",
    "collections/Walking/Walking_21.jpg": "Image description",
    "collections/Walking/Walking_22.jpg": "Image description",
    "collections/Walking/Walking_23.jpg": "Image description",
    "collections/Walking/Walking_24.jpg": "Image description",
    "collections/Walking/Walking_25.jpg": "Image description",
    "collections/Walking/Walking_26.jpg": "Image description",
    "collections/Walking/Walking_27.jpg": "Image description",
    "collections/Walking/Walking_28.jpg": "Image description",
    "collections/Walking/Walking_29.jpg": "Image description",
    "collections/Walking/Walking_30.jpg": "Image description",
    "collections/Walking/Walking_31.jpg": "Image description",
    "collections/Walking/Walking_32.jpg": "Image description",
    "collections/Walking/Walking_33.jpg": "Image description",
    "collections/homepage/ascii-art (3).png": "Image description",
    "collections/homepage/ascii-art (4).png": "Image description",
    "collections/homepage/Belgrade_1.jpg": "Image description",
    "collections/homepage/Belgrade_4.jpg": "Image description",
    "collections/homepage/Chroma_0.jpg": "Image description",
    "collections/homepage/dark-icon.png": "Image description",
    "collections/homepage/Fan_tail_L.jpg": "Image description",
    "collections/homepage/Harbour.jpg": "Image description",
    "collections/homepage/light-icon.png": "Image description",
    "collections/homepage/magnifier-icon.png": "Image description",
    "collections/homepage/TuiPark_Kauri_Park.jpg": "Image description"
};

// ============================================================
// GET DESCRIPTION FUNCTION
// ============================================================
function getImageDescription(path) {
    if (CUSTOM_DESCRIPTIONS[path]) {
        return CUSTOM_DESCRIPTIONS[path];
    }
    const filename = path.split('/').pop();
    const name = filename.replace(/\.[^/.]+$/, '');
    return name.replace(/[-_]/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}