const MASTER_IMAGE_REGISTRY = [
    "collections/Belgrade/Belgrade_1.jpg",
    "collections/Belgrade/Belgrade_10.jpg",
    "collections/Belgrade/Belgrade_11.jpg",
    "collections/Belgrade/Belgrade_12.jpg",
    "collections/Belgrade/Belgrade_13.jpg",
    "collections/Belgrade/Belgrade_14.jpg",
    "collections/Belgrade/Belgrade_15.jpg",
    "collections/Belgrade/Belgrade_16.jpg",
    "collections/Belgrade/Belgrade_17.jpg",
    "collections/Belgrade/Belgrade_18.jpg",
    "collections/Belgrade/Belgrade_19.jpg",
    "collections/Belgrade/Belgrade_2.jpg",
    "collections/Belgrade/Belgrade_3.jpg",
    "collections/Belgrade/Belgrade_4.jpg",
    "collections/Belgrade/Belgrade_5.jpg",
    "collections/Belgrade/Belgrade_6.jpg",
    "collections/Belgrade/Belgrade_7.jpg",
    "collections/Belgrade/Belgrade_8.jpg",
    "collections/Belgrade/Belgrade_9.jpg",
    "collections/Chroma/Chroma_0.jpg",
    "collections/Chroma/Chroma_1.jpg",
    "collections/Chroma/Chroma_10.jpg",
    "collections/Chroma/Chroma_11.jpg",
    "collections/Chroma/Chroma_12.jpg",
    "collections/Chroma/Chroma_13.jpg",
    "collections/Chroma/Chroma_14.jpg",
    "collections/Chroma/Chroma_15.jpg",
    "collections/Chroma/Chroma_16.jpg",
    "collections/Chroma/Chroma_17.jpg",
    "collections/Chroma/Chroma_18.jpg",
    "collections/Chroma/Chroma_19.jpg",
    "collections/Chroma/Chroma_2.jpg",
    "collections/Chroma/Chroma_20.jpg",
    "collections/Chroma/Chroma_21.jpg",
    "collections/Chroma/Chroma_3.jpg",
    "collections/Chroma/Chroma_4.jpg",
    "collections/Chroma/Chroma_5.jpg",
    "collections/Chroma/Chroma_6.jpg",
    "collections/Chroma/Chroma_7.jpg",
    "collections/Chroma/Chroma_8.jpg",
    "collections/Chroma/Chroma_9.jpg",
    "collections/Hangzhou/Hangzhou_1.jpg",
    "collections/Hangzhou/Hangzhou_10.jpg",
    "collections/Hangzhou/Hangzhou_11.jpg",
    "collections/Hangzhou/Hangzhou_12.jpg",
    "collections/Hangzhou/Hangzhou_13.jpg",
    "collections/Hangzhou/Hangzhou_14.jpg",
    "collections/Hangzhou/Hangzhou_15.jpg",
    "collections/Hangzhou/Hangzhou_16.jpg",
    "collections/Hangzhou/Hangzhou_17.jpg",
    "collections/Hangzhou/Hangzhou_18.jpg",
    "collections/Hangzhou/Hangzhou_19.jpg",
    "collections/Hangzhou/Hangzhou_2.jpg",
    "collections/Hangzhou/Hangzhou_20.jpg",
    "collections/Hangzhou/Hangzhou_3.jpg",
    "collections/Hangzhou/Hangzhou_4.jpg",
    "collections/Hangzhou/Hangzhou_5.jpg",
    "collections/Hangzhou/Hangzhou_6.jpg",
    "collections/Hangzhou/Hangzhou_7.jpg",
    "collections/Hangzhou/Hangzhou_8.jpg",
    "collections/Hangzhou/Hangzhou_9.jpg",
    "collections/homepage/ascii-art (3).png",
    "collections/homepage/ascii-art (4).png",
    "collections/homepage/Belgrade_1.jpg",
    "collections/homepage/Belgrade_4.jpg",
    "collections/homepage/Chroma_0.jpg",
    "collections/homepage/dark-icon.png",
    "collections/homepage/Fan_tail_L.jpg",
    "collections/homepage/Harbour.jpg",
    "collections/homepage/light-icon.png",
    "collections/homepage/magnifier-icon.png",
    "collections/homepage/TuiPark_Kauri_Park.jpg",
    "collections/Music/Music_1.jpg",
    "collections/Music/Music_10.jpg",
    "collections/Music/Music_11.jpg",
    "collections/Music/Music_12.jpg",
    "collections/Music/Music_13.jpg",
    "collections/Music/Music_14.jpg",
    "collections/Music/Music_15.jpg",
    "collections/Music/Music_16.jpg",
    "collections/Music/Music_17.jpg",
    "collections/Music/Music_18.jpg",
    "collections/Music/Music_19.jpg",
    "collections/Music/Music_2.jpg",
    "collections/Music/Music_20.jpg",
    "collections/Music/Music_21.jpg",
    "collections/Music/Music_22.jpg",
    "collections/Music/Music_23.jpg",
    "collections/Music/Music_24.jpg",
    "collections/Music/Music_25.jpg",
    "collections/Music/Music_3.jpg",
    "collections/Music/Music_4.jpg",
    "collections/Music/Music_5.jpg",
    "collections/Music/Music_6.jpg",
    "collections/Music/Music_7.jpg",
    "collections/Music/Music_8.jpg",
    "collections/Music/Music_9.jpg",
    "collections/South Island/South Island_1.jpg",
    "collections/South Island/South Island_10.jpg",
    "collections/South Island/South Island_11.jpg",
    "collections/South Island/South Island_12.jpg",
    "collections/South Island/South Island_13.jpg",
    "collections/South Island/South Island_14.jpg",
    "collections/South Island/South Island_15.jpg",
    "collections/South Island/South Island_16.jpg",
    "collections/South Island/South Island_17.jpg",
    "collections/South Island/South Island_18.jpg",
    "collections/South Island/South Island_19.jpg",
    "collections/South Island/South Island_2.jpg",
    "collections/South Island/South Island_20.jpg",
    "collections/South Island/South Island_21.jpg",
    "collections/South Island/South Island_22.jpg",
    "collections/South Island/South Island_23.jpg",
    "collections/South Island/South Island_24.jpg",
    "collections/South Island/South Island_3.jpg",
    "collections/South Island/South Island_4.jpg",
    "collections/South Island/South Island_5.jpg",
    "collections/South Island/South Island_6.jpg",
    "collections/South Island/South Island_7.jpg",
    "collections/South Island/South Island_8.jpg",
    "collections/South Island/South Island_9.jpg",
    "collections/Walking/Walking_1.jpg",
    "collections/Walking/Walking_10.jpg",
    "collections/Walking/Walking_11.jpg",
    "collections/Walking/Walking_12.jpg",
    "collections/Walking/Walking_13.jpg",
    "collections/Walking/Walking_14.jpg",
    "collections/Walking/Walking_15.jpg",
    "collections/Walking/Walking_16.jpg",
    "collections/Walking/Walking_17.jpg",
    "collections/Walking/Walking_18.jpg",
    "collections/Walking/Walking_19.jpg",
    "collections/Walking/Walking_2.jpg",
    "collections/Walking/Walking_20.jpg",
    "collections/Walking/Walking_21.jpg",
    "collections/Walking/Walking_22.jpg",
    "collections/Walking/Walking_23.jpg",
    "collections/Walking/Walking_24.jpg",
    "collections/Walking/Walking_25.jpg",
    "collections/Walking/Walking_26.jpg",
    "collections/Walking/Walking_27.jpg",
    "collections/Walking/Walking_28.jpg",
    "collections/Walking/Walking_29.jpg",
    "collections/Walking/Walking_3.jpg",
    "collections/Walking/Walking_30.jpg",
    "collections/Walking/Walking_31.jpg",
    "collections/Walking/Walking_32.jpg",
    "collections/Walking/Walking_33.jpg",
    "collections/Walking/Walking_4.jpg",
    "collections/Walking/Walking_5.jpg",
    "collections/Walking/Walking_6.jpg",
    "collections/Walking/Walking_7.jpg",
    "collections/Walking/Walking_8.jpg",
    "collections/Walking/Walking_9.jpg"
];

// ============================================================
// CUSTOM TITLES (short text, replaces the filename)
// ============================================================
const IMAGE_TITLES = {
    // ---- BELGRADE ----
    "collections/Belgrade/Belgrade_2.jpg": "The Danube River",
    "collections/Belgrade/Belgrade_5.jpg": "neighborhood",
    "collections/Belgrade/Belgrade_6.jpg": "neighborhood cat",
    "collections/Belgrade/Belgrade_7.jpg": "IV8",
    "collections/Belgrade/Belgrade_8.jpg": "snowman",
    "collections/Belgrade/Belgrade_9.jpg": "untitled IV8 Vuja Rile oda",
    "collections/Belgrade/Belgrade_10.jpg": "Sinkhole",
    "collections/Belgrade/Belgrade_11.jpg": "Yankee Go Home",
    "collections/Belgrade/Belgrade_12.jpg": "Yankee Go Home",
    "collections/Belgrade/Belgrade_13.jpg": "Gospoda Marjan Pušika",
    "collections/Belgrade/Belgrade_14.jpg": "Kalemegdan Basketball Courts",
    "collections/Belgrade/Belgrade_15.jpg": "Kalemegdan Park",
    "collections/Belgrade/Belgrade_16.jpg": "Parked car, double exposure",
    "collections/Belgrade/Belgrade_17.jpg": "Kalemegdan Basketball Courts",
    "collections/Belgrade/Belgrade_18.jpg": "Zeleni Venac Market",
    "collections/Belgrade/Belgrade_19.jpg": "Street",

    // ---- CHROMA ----
    "collections/Chroma/Chroma_0.jpg": "Mona Lisa",
    "collections/Chroma/Chroma_1.jpg": "Wither Hills, Blenheim",
    "collections/Chroma/Chroma_2.jpg": "Auckland Harbour Bridge",
    "collections/Chroma/Chroma_3.jpg": "Auckland Harbour Bridge",
    "collections/Chroma/Chroma_4.jpg": "Distinction Hotel facade, Christchurch",
    "collections/Chroma/Chroma_5.jpg": "Dog, Christchurch",
    "collections/Chroma/Chroma_6.jpg": "Ratcliffe-on-Soar Power Station, Nottinghamshire",
    "collections/Chroma/Chroma_7.jpg": "Northern Explorer, River",
    "collections/Chroma/Chroma_8.jpg": "Northern Explorer",
    "collections/Chroma/Chroma_9.jpg": "Northern Explorer, Grazing Cows",
    "collections/Chroma/Chroma_10.jpg": "Pointing Stick, Mount Ruapehu",
    "collections/Chroma/Chroma_11.jpg": "Birdseye View of a Cat",
    "collections/Chroma/Chroma_12.jpg": "Jacqueline Fraser",
    "collections/Chroma/Chroma_13.jpg": "European Police Horses",
    "collections/Chroma/Chroma_14.jpg": "Laundromat",
    "collections/Chroma/Chroma_16.jpg": "Taniwha, Whataitai,",
    "collections/Chroma/Chroma_17.jpg": "Northern Explorer's, Mount Ruapehu",
    "collections/Chroma/Chroma_18.jpg": "Auckland Central Parish Pitt Street Methodist Church",
    "collections/Chroma/Chroma_19.jpg": "Elmo, Auckland Christmas Parade",
    "collections/Chroma/Chroma_20.jpg": "Elmo, Auckland Christmas Parade",
    "collections/Chroma/Chroma_21.jpg": "Pigeons, (Deceased)",
};

// ============================================================
// CUSTOM DESCRIPTIONS (long text, replaces the auto‑generated description)
// ============================================================
const IMAGE_DESCRIPTIONS = {
    "collections/Belgrade/Belgrade_1.jpg": "The Danube River - froze over 2017, these deep freezes have notably happened in 2012 and 2017 - halting commercial shipping routes.",
    "collections/Belgrade/Belgrade_3.jpg": "McDonald's Zeleni Venac restaurant located at Zeleni Venac in Belgrade, Serbia",
    "collections/Belgrade/Belgrade_4.jpg": "palata glavne pošte headquarters of Pošta Srbije, national postal service of Serbia.",
};

// ============================================================
// GET TITLE & DESCRIPTION FUNCTIONS
// ============================================================
function getImageTitle(path) {
    if (IMAGE_TITLES[path]) {
        return IMAGE_TITLES[path];
    }
    // fallback: generate from filename
    const filename = path.split('/').pop();
    return filename.replace(/\.[^/.]+$/, '').replace(/[-_]/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}

function getImageDescription(path) {
    if (IMAGE_DESCRIPTIONS[path]) {
        return IMAGE_DESCRIPTIONS[path];
    }
    // fallback: auto-generate from filename
    const filename = path.split('/').pop();
    const name = filename.replace(/\.[^/.]+$/, '');
    return name.replace(/[-_]/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}